### ISSUE TITLE
cannot import name 'BalancingSubSampler' from 'src.data.datasets'

### ISSUE THREAD

**Issue by LiubovSobolevskaya** [SamusRam/hpa-single-cell#5]
I ran into another issue.
When I call
```bash 
python -m src.train.train_bestfitting
```
the following line
```python 
from ..data.datasets import ProteinDatasetImageLevel, BalancingSubSampler
```
causes the following ImportError:
```bash 
cannot import name 'BalancingSubSampler' from 'src.data.datasets'

**Comment by SamusRam** [comment]
Fixed! Thanks for reporting the bug 👍 

FYI, I didn't have time to experiment with balancing the training data, so this code won't be used if you follow the README, but otherwise, it might be interesting to experiment with it ;)
